### ISSUE TITLE
Indentation of second-level bullets is undesirably removed

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#42] opened 2019-08-18 17:22 UTC
Example input file: [BancorConverter.sol](https://github.com/bancorprotocol/contracts/blob/master/solidity/contracts/converter/BancorConverter.sol).

Example output file: [BancorConverter.md](https://github.com/bancorprotocol/contracts/blob/master/solidity/docgen/docs/converter/BancorConverter.md).

As you can see, at the top of the input file, under `Open issues:` there is a single bullet which is detailed into 3 secondary bullets.

However, the indentation of these secondary bullets is removed by `solidity-docgen`, thus turning them into "first-level" bullets.

It might be more visible if you view the output file in Edit format, by clicking the Pencil button at the top-right corner (or simply [here](https://github.com/bancorprotocol/contracts/edit/master/solidity/docgen/docs/converter/BancorConverter.md)).

Thanks

**Comment by frangio** [comment] 2019-08-30 16:58
This is caused by the following line:

https://github.com/OpenZeppelin/solidity-docgen/blob/4f9aa2d6ce5a75349fdf72b97f7d3e1ea21cf109/src/solidity.ts#L302

The regexp matches an asterisk followed by any number of spaces or tabs, and removes that. Perhaps it should only match a single space after the asterisk.

**Comment by barakman** [comment] 2019-09-01 07:58
The suggestion given [here](https://github.com/OpenZeppelin/solidity-docgen/issues/41#issuecomment-526672762) solves this problem.

**Comment by frangio** [comment] 2019-10-29 22:18
I don't think it will be possible to implement a fix for this without breaking the parsing of doc comments where every line is prefixed with an asterisk.

**Closed by frangio** 2019-10-29 22:18 UTC
