### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by cartercarlson** [OpenZeppelin/solidity-docgen#407] opened 2022-08-29 22:28 UTC
New error @frangio :
```
$ npx hardhat docgen
Nothing to compile
No need to generate any newer typings.
An unexpected error occurred:

Error: Circular dependency detected: aliased imports not supported
    at run (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/scope.ts:16:15)
    at run (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/scope.ts:36:29)
    at run (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/scope.ts:36:29)
    at run (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/scope.ts:36:29)
    at getContractsInScope (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/scope.ts:7:10)
    at parseNatspec (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/natspec.ts:103:49)
    at natspec (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/common/properties.ts:18:22)
    at /home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/site.ts:103:53
    at Object.get (/home/carter/Documents/metokens/metokens-core/node_modules/solidity-docgen/src/utils/memoized-getter.ts:16:19)
    at lookupProperty (/home/carter/Documents/metokens/metokens-core/node_modules/handlebars/lib/handlebars/runtime.js:130:26)
```

_Originally posted by @cartercarlson in https://github.com/OpenZeppelin/solidity-docgen/issues/406#issuecomment-1230888961_

**Comment by frangio** [comment] 2022-08-30 03:59
Thanks for reporting. This is a separate issue that is caused by lack of support for circular dependencies in Solidity files when aliased imports are used (`import { A as B } from './A.sol'`). I have an idea for how to add support, but as a workaround you can either remove the circular dependencies or the aliasing.

If you are not using that syntax let me know because the error would be something else.

**Comment by frangio** [comment] 2022-08-30 04:14
Ok the circular dependencies issue should be fixed in latest by https://github.com/OpenZeppelin/solidity-docgen/commit/a1215b65d38483296b5c98f86f8e8fff529edcd3. Let me know if that fixed it for you.

**Closed by frangio** 2022-08-30 04:14 UTC
