### ISSUE TITLE
Bug: Using unicode may cause some code after the comments to be rendered

### ISSUE THREAD

**Issue by htadashi** [OpenZeppelin/solidity-docgen#387] opened 2022-06-02 04:51 UTC
Usage of the unicode '⇌' seems to break OpenZeppelin docs. For each ⇌ introduced, more characters from outside the comments are included (e.g. "/ contract CrossCha" in the figure below).  

![image](https://user-images.githubusercontent.com/2355491/171496092-c575f725-2739-4370-9301-0810de2e3d53.png)
(From https://docs.openzeppelin.com/contracts/4.x/api/crosschain#CrossChainEnabledAMB)

**How to reproduce**
Run `yarn docs:watch` in https://github.com/OpenZeppelin/openzeppelin-contracts/commit/4574ce45b65c780afea020cdac2c6e99230d8609. Removing ⇌ causes the proper rendering.

**Comment by frangio** [comment] 2022-06-10 21:09
Thanks @htadashi. The problem is that the Solidity AST uses byte indices and we're using those as if they were character indices and this fails for multi-byte characters.

Fixed in a52917237eed6cd7ad1fea5a280596bcfe43405e for 0.5 and ba4868bc3dea537768f690c3e84e29903bdc6f15 for 0.6.

**Closed by frangio** 2022-06-10 21:09 UTC

**Comment by htadashi** [comment] 2022-06-12 08:32
@frangio Thanks for the fix and the explanation. I always learn something from your commits :)
