### ISSUE TITLE
TypeError: importedScope[a.foreign.name] is not a function

### ISSUE THREAD

**Issue by GopherJ** [OpenZeppelin/solidity-docgen#415] opened 2022-10-17 04:39 UTC
we encountered this issue in https://github.com/para-space/paraspace-core
![image](https://user-images.githubusercontent.com/33961674/196090573-ac2c62a0-b85e-415e-b391-d0a85f9d5c0e.png)

**Comment by leovigna** [comment] 2022-11-11 14:22
Had the same issue. Debugged this manually by ignoring files to isolate what file was causing the issue. Source code mentioned "// Delayed function call supports circular dependencies" but it seems the issue was stemming from `@inheritdoc` doc statements in an abstract contract.

When I had `GrandChild -> Child -> Parent` dependency with a `@inheritdoc Child` in the GrandChild contract, it worked for some of my non-abstract contracts so nested @inheritdoc seems to be working but just throws with my 1 abstract contract with the same configuration. For now as a quick fix, I just removed the @inheritdoc statements that would break solidity-docgen.

Hope this helps!

**Comment by frangio** [comment] 2022-11-11 23:12
Can you share the full source code that reproduces the issue?

**Comment by CarterAppleton** [comment] 2022-11-29 19:32
We're also experiencing this, you can repro on this commit of goldfinch-eng/mono

https://github.com/goldfinch-eng/mono/tree/4ffb02ed3363fd658eb144b52e59340e44e0e104

it's a monorepo so installation has some steps
- make sure python is installed (I use 2.7.18 to build)
- run `npx lerna bootstrap` at the repo root to set up all packages
- cd into `packages/docs`
- run `npm run build-contract-docs` to repro issue

We've fixed it temporarily by removing various `@inheritdoc` until it passed, but definitely not the ideal solution

**Comment by frangio** [comment] 2022-11-29 20:49
Thanks. There was an error when using the syntax `import {E} from ...` and the imported symbols were not contracts (e.g. custom errors). This should be fixed in the latest version.

**Closed by frangio** 2022-11-29 20:49 UTC

**Comment by lnist** [comment] 2022-12-02 09:28
@frangio : I think `///@inheritdoc` also fails in another case. Should I open a new issue?

A minimal example:

ImportedAs.sol
```
pragma solidity ^0.8.10;
```

Lib.sol
```
pragma solidity ^0.8.10;

import "./ImportedAs.sol" as ImportedAs;
```

Root.sol
```
pragma solidity ^0.8.10;

import {ImportedAs} from "./Lib.sol";

contract A {
   function f() internal virtual {}
}

contract B is A {
  ///@inheritdoc A
  function f() internal override {}
}
```

**Comment by frangio** [comment] 2022-12-02 14:18
I'll take a look but please open another issue. The problem is probably lack of suport for `import "" as X;` syntax.
